ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include

from cart import views

app_name="cart"

urlpatterns = [
path('addtocart/<n>', views.addtocart, name="addtocart"),
path('cartremove/<n>', views.cartremove, name="cartremove"),
path('trash/<n>', views.trash, name="trash"),
path('cartview', views.cartview, name="cartview"),
path('orderform', views.orderform, name="orderform"),
path('orderview',views.orderview,name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include

from search import views

app_name="search"

urlpatterns = [
path('search', views.search, name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path


from shop import views

app_name="shop"

urlpatterns = [

    path('',views.allcategories,name="category"),
    path('product/<str:p>/',views.productdetails,name="productdetails"),
    path('details/<str:p>/',views.details,name="details"),
    path('userlogin', views.userlogin, name="userlogin"),
    path('register', views.register, name="register"),
    path('userlogout', views.userlogout, name="userlogout"),

]

ecommerce/cart/models.py
from django.db import models

from shop.models import Product

from django.contrib.auth.models import User

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Product.name

    def subtotal(self):
        return self.quantity*self.product.price


class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status= models.CharField(max_length=20, default="pending")

    def __str__(self):
        return self.product.name


class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart, Account, Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def cartview(request):
    u = request.user  # current login user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total+=i.quantity*i.product.price
    return render(request, 'cartview.html',{'c':cart,'total':total})


@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user #current login user

    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.product.stock>0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock>0):
         cart = Cart.objects.create(product=p, user=u, quantity=1)
         cart.save()
         p.stock-=1
         p.save()


    return cartview(request)


@login_required
def cartremove(request,n):
    p = Product.objects.get(name=n)
    u = request.user  # current login user

    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()

        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
        pass

    return cartview(request)



@login_required
def trash(request,n):
    p = Product.objects.get(name=n)
    u = request.user  # current login user

    try:
      cart = Cart.objects.get(user=u, product=p)
      cart.delete()

      p.stock+=cart.quantity
      p.save()

    except:
        pass

    return cartview(request)


@login_required
def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total = 0
        for i in cart:
            total += i.quantity * i.product.price

        try:
            num=int(n)
            ac=Account.objects.get(acctnum=num)
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="your Order placed Successfully"
                return render(request,'orderdetail.html',{'msg':msg})

            else:
                msg="Insufficient amount. You can't place order"
                return render(request, 'orderdetail.html', {'msg': msg})

        except:
            pass


    return render(request,'orderform.html')


@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render

from django.db.models import Q

from shop.models import Product

# Create your views here.
def search(request):
    query = ""
    p = None
    if (request.method == "POST"):
        query = request.POST['q']
        if (query):
            products =Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request, 'search.html', {'query': query, 'p': products})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ecommerce</title>
<!--    bootstrap link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<!--    google fonts link-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">

<!--    css link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

<!--    font awesome link-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
   <header>
       <div class="container-fluid" id="logo">
           <center><img src="{% static 'images/ecommercelogo.png' %}" height="100px" width="100px" ></center>
       </div>
   </header>

<!--   navbar-->
<div id="nav">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">NEST</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:category' %}">Home</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Home</a>-->
<!--        </li>-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ALL CATEGORIES
          </a>
          <ul class="dropdown-menu">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:productdetails' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
          {% if user.is_authenticated %}

            <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:userlogout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}
          <li>
          <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sub class="ms-1">{{count}}</sub></i></a>
        </li>
          <li>
          <a class="nav-link" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}

          {% else %}
          <li>
          <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li>
          <a class="nav-link" href="{% url 'shop:userlogin' %}">Login</a>
        </li>
          {% endif %}

      </ul>
      <form class="d-flex" role="search" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>
{% block content %}

   {% endblock %}

<footer>
    <div class="footer">
        <p><i class="fa-solid fa-copyright">NEST shop@pvt.ltd.All rights reserved.</i></p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="
margin-bottom:100px">
  <div class="row">
    <h4 class="text-center">Shopping Cart</h4>

    <div class="col-6">
    <table class="table table-bordered text-center fs-5">
      <tr>
        <th colspan="5">Cart Items</th>
      </tr>
      {% for i in c %}
      <tr>
        <td><img src="{{i.product.image.url}}" height="100px" width="100px"><</td>
        <td><b>{{i.product.name}}</b></td>
        <td>
          <b>ProductID:{{i.product.id}}</b><br>
          <b>Unit Price:{{i.product.price}}</b><br>
          <b>Quantity:{{i.quantity}}</b><br>

        </td>
        <td>
          <b>subtotal:{{i.subtotal}}</b>
        </td>
        <td>
          {% if i.product.stock > 0 %}
          <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger fs-4"></i></a>
          <a href="{% url 'cart:cartremove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
          <a href="{% url 'cart:trash' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>
        {% else %}
        <a href="{% url 'cart:cartremove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
          <a href="{% url 'cart:trash' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>
        {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
    </div>


    <div class="col-4 fs-5 ms-3" style="position:relative">
    <table class="table table-bordered">
      <tr>
        <th colspan="3">Check Out</th>
       <tr>
      <th>
        TOTAL AMOUNT:<span style="position:absolute;right:20px;">{{total}}</span>
      </th>
      </tr>
    </table>
      <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
      <a href="{% url 'shop:category' %}" class="btn btn-danger" style="position:absolute;right:20px;">Continue Shopping</a>
    </div>

  </div>

</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/img.png' %}" height="450px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;" >
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>

<!-- templates/your_app/product_list.html -->
<div class="container-fluid mt-3" style="margin-bottom:100px;">
  <div class="row">
    {% for i in c %}
      <div class="col mt-4 ">
        <div class="card" style="width: 30rem;">
          <img src="{{ i.image.url }}" class="card-img-top" alt="{{ i.name }}" height="200px" width="100%">
          <div class="card-body">
            <h5 class="card-title text-center fw-bold" >{{ i.name }}</h5>
<!--            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
            <a href="{% url 'shop:productdetails' i.name %}" class="btn btn-primary">Products</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col-sm-4 me-5">
      <img src="{{ p.image.url }}" class="card-img-top" height="300px" width="100%">
    </div>
    <div class="col-sm-6 me-5">
       <h4>{{ p.name }}</h4>
         <p class="h4 mt-5 lh-base" >{{ p.desc }}</p>
        <h2 class="mt-4" >{{ p.price }}</h2>
      {{p.stock}}
      {% if user.is_superuser == True %}
      {% if p.stock == 0 %}

      <h2>out of stock</h2>
      <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD TO CART</a>
      {% else %}
      <h2>Product in stock</h2>
      <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
      {% endif %}

      {% else %}

        {% if p.stock == 0 %}
      <h2>out of stock</h2>
      {% else %}
      <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger mt-5">ADD TO CART</a>
      {% endif %}

      {% endif %}

    </div>

  </div>
</div>


{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="enter the username">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>
  <div class="mb-3">
  <input type="submit" class="form-control">
  </div>
</form>
  </center>
{% endblock %}

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <center>
        <h4 class="text-center text-success">{{msg}}</h4>
        <h4 class="text-center text-danger">Thank You....</h4>
        <h4 class="text-center"><a href="{% url 'shop:category' %}">Continue Shopping</a></h4>
    </center>
</div>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom=100px;" >
    <center>
<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="enter the address">
  </div>
      <div class="mb-3">
    <label class="form-label">Phone</label>
    <input type="number" class="form-control" name="p" placeholder="enter the phonenumber">
  </div>
    <div class="mb-3">
    <label class="form-label">Account Number</label>
    <input type="number" class="form-control" name="n" placeholder="enter the account number">
  </div>
 <div class="mb-3">
  <input type="submit" class="form-control">
  </div>
</form>
        </center>
</div>

    {% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row mt-5 border border-1">
      <h4>Name of the customer:{{u}}</h4>
      {% for i in o %}
      <div class="col-sm-4 me-5">
      <img src="{{ i.product.image.url }}"  height="200px" width="200%">
    </div>
    <div class="col-sm-6 me-5 text-center">
       <b>Product name:{{i.product.name}}</b><br>
        <b>Product Price:{{i.product.price}}</b><br>
        <b>Delivery_address:{{i.address}}</b><br>
        <b>Customer Phone:{{i.phone}}</b><br>
        <b>Product name:{{i.product.name}}</b><br>
        <b>Order on:{{i.ordered_date}}</b><br>
        <b class="text-success">Delivery_status{{ i.delivery.status}}</b>
        {% endfor %}
    </div>

  </div>
</div>


{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="450px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h5 class="text-center fw-bold" >{{ c.name }}</h5>
    <p style="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
  <div class="row">
    {% for i in p %}
      <div class="col mt-4 ">
        <div class="card" style="width: 30rem;">
          <img src="{{ i.image.url }}" class="card-img-top" alt="{{ i.name }}" height="200px" width="100%">
          <div class="card-body">
            <h5 class="card-title text-center fw-bold" >{{ i.name }}</h5>
<!--            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
            <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Products</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom=100px;" >
<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="enter the username">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>
    <div class="mb-3">
    <label  class="form-label">Confirm password</label>
    <input type="text" class="form-control" name="cp" placeholder="enter the password again">
  </div>
     <div class="mb-3">
    <label  class="form-label">firstname</label>
    <input type="text" class="form-control" name="f" placeholder="enter the first name">
  </div>
     <div class="mb-3">
    <label  class="form-label">lastname</label>
    <input type="text" class="form-control" name="l" placeholder="enter the last name">
  </div>
     <div class="mb-3">
    <label  class="form-label">emailaddress</label>
    <input type="email" class="form-control" name="e" placeholder="enter the email">
  </div>
  <div class="mb-3">
  <input type="submit" class="form-control">
  </div>
</form>
  </div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom=100px;" ></div>
<center>
  <h5>you have searched for {{query}}</h5>
  {% if p %}
   <div class="row">
    {% for i in p %}
      <div class="col mt-4 ">
        <div class="card" style="width: 30rem;">
          <img src="{{ i.image.url }}" class="card-img-top" alt="{{ i.name }}" height="200px" width="100%">
          <div class="card-body">
            <h5 class="card-title text-center fw-bold" >{{ i.name }}</h5>
<!--            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
            <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Products</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% endif %}

</center>

{% endblock %}